// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const site: { "brandName": string; "navigation": Array<{ "label": string; "href": string; "id": string }>; "footerLink": { "label": string; "href": string }; "copyright": string };
  export const pages: { "home": { "hero": { "label": string; "title": string; "support": string; "footerNote": string; "linkLabel": string; "linkHref": string } }; "runtime_lab": { "eyebrow": string; "title": string; "description": string; "cards": Array<{ "id": string; "title": string; "body": string; "action": string }>; "cacheLabel": string; "cachePlaceholder": string; "primeLabel": string; "primePlaceholder": string; "outputTitle": string; "idleMessage": string } };
  export const home: { "hero": { "label": string; "title": string; "support": string; "footerNote": string; "linkLabel": string; "linkHref": string } };
  export const runtime_lab: { "eyebrow": string; "title": string; "description": string; "cards": Array<{ "id": string; "title": string; "body": string; "action": string }>; "cacheLabel": string; "cachePlaceholder": string; "primeLabel": string; "primePlaceholder": string; "outputTitle": string; "idleMessage": string };
}
